# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn_algo',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/learn_algo',
                'lib_path': 'learn_algo'},
  'syms': {'learn_algo.core': {'learn_algo.core.foo': ('core.html#foo', 'learn_algo/core.py')}}}
